use_frameworks!

platform :ios, '9.0'

target 'ZWUniversalComponent_Example' do
  pod 'ZWUniversalComponent', :path => '../'

  target 'ZWUniversalComponent_Tests' do
    inherit! :search_paths

    
  end
end
